import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { checkRateLimit } from '@/lib/rate-limit'

const DEFAULT_REQUESTED_PERMISSIONS = [
  'view_profile',
  'view_assessment_results',
  'view_assessment_history',
  'message_patient',
]

export async function POST(request: Request) {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  // Verify role = 'clinician'
  const { data: profile } = await supabase
    .from('profiles')
    .select('role')
    .eq('id', user.id)
    .single()

  if (!profile || profile.role !== 'clinician') {
    return NextResponse.json({ error: 'Forbidden: clinician role required' }, { status: 403 })
  }

  // Verify clinician is verified
  const { data: verification } = await supabase
    .from('clinician_verifications')
    .select('id, status')
    .eq('clinician_id', user.id)
    .eq('status', 'verified')
    .maybeSingle()

  if (!verification) {
    return NextResponse.json(
      { error: 'Clinician account must be verified before sending invitations' },
      { status: 403 }
    )
  }

  // Rate limit: 20 invitations per day
  const rateLimit = await checkRateLimit(`clinician_invite:${user.id}`, {
    limit: 20,
    windowMs: 24 * 60 * 60 * 1000,
  })
  if (!rateLimit.allowed) {
    return NextResponse.json(
      { error: 'Daily invitation limit reached. You may send up to 20 invitations per day.' },
      { status: 429 }
    )
  }

  let body: Record<string, unknown> = {}
  try {
    const text = await request.text()
    if (text) body = JSON.parse(text)
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const message =
    typeof body.message === 'string' ? body.message.trim() || null : null

  const requested_permissions =
    Array.isArray(body.requested_permissions) && body.requested_permissions.length > 0
      ? (body.requested_permissions as string[])
      : DEFAULT_REQUESTED_PERMISSIONS

  const admin = createAdminClient()

  // Insert invitation — token generated by DB DEFAULT
  const { data: invitation, error: insertError } = await admin
    .from('clinician_invitations')
    .insert({
      clinician_id: user.id,
      message,
      requested_permissions,
    })
    .select('id, token, status, message, requested_permissions, created_at, expires_at')
    .single()

  if (insertError || !invitation) {
    console.error('[POST /api/clinician/invite] insert error:', insertError)
    return NextResponse.json({ error: 'Failed to create invitation' }, { status: 500 })
  }

  // Write audit log
  const { error: auditError } = await admin.from('audit_log').insert({
    action: 'invitation_created',
    actor_id: user.id,
    target_type: 'clinician_invitation',
    target_id: invitation.id,
  })

  if (auditError) {
    console.error('[POST /api/clinician/invite] audit log error:', auditError)
  }

  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? ''
  const invite_url = `${siteUrl}/connect/${invitation.token}`

  return NextResponse.json({ invitation, invite_url }, { status: 201 })
}

export async function GET() {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  // Verify role = 'clinician'
  const { data: profile } = await supabase
    .from('profiles')
    .select('role')
    .eq('id', user.id)
    .single()

  if (!profile || profile.role !== 'clinician') {
    return NextResponse.json({ error: 'Forbidden: clinician role required' }, { status: 403 })
  }

  const { data: invitations, error } = await supabase
    .from('clinician_invitations')
    .select('id, token, status, message, requested_permissions, created_at, expires_at, accepted_at, patient_id')
    .eq('clinician_id', user.id)
    .order('created_at', { ascending: false })
    .limit(50)

  if (error) {
    console.error('[GET /api/clinician/invite] query error:', error)
    return NextResponse.json({ error: 'Failed to fetch invitations' }, { status: 500 })
  }

  return NextResponse.json({ invitations: invitations ?? [] })
}
