import { View, Text, ScrollView, TouchableOpacity, StyleSheet } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { useLocalSearchParams, useRouter } from 'expo-router'
import { Ionicons } from '@expo/vector-icons'
import { useLocale, useIsRTL } from '@/lib/hooks'
import { t } from '@/lib/i18n'
import { RESOURCES } from './index'

const ARTICLE_CONTENT: Record<string, { en: string; ar: string }> = {
  'understanding-your-anxiety': {
    en: `Anxiety is one of the most common mental health experiences in the world. It manifests as worry, fear, or unease about future events — sometimes rational, sometimes out of proportion to the actual threat. Understanding why your mind and body respond this way is the first step to managing it.\n\nAt its core, anxiety is your brain's alarm system. When you perceive a threat, your amygdala fires, releasing stress hormones like cortisol and adrenaline. Your heart rate increases, your breathing quickens, and your muscles tense — the classic "fight or flight" response. This is helpful when facing real danger, but becomes problematic when it triggers over everyday situations.\n\nCommon symptoms of anxiety include persistent worry, difficulty concentrating, irritability, muscle tension, sleep disturbances, and physical symptoms like a racing heart or sweating. Not everyone experiences anxiety the same way, and recognizing your personal pattern is key.\n\nThe good news is that anxiety is highly treatable. Cognitive Behavioral Therapy (CBT), mindfulness practices, medication when appropriate, and lifestyle changes have all been shown to reduce anxiety significantly. The first step is acknowledging what you are experiencing and reaching out for support.`,
    ar: `القلق هو أحد أكثر تجارب الصحة النفسية شيوعاً في العالم. يتجلى في شكل قلق أو خوف أو انزعاج من الأحداث المستقبلية — أحياناً بشكل عقلاني وأحياناً بشكل غير متناسب مع التهديد الفعلي. فهم سبب استجابة عقلك وجسمك بهذه الطريقة هو الخطوة الأولى للتعامل معه.\n\nفي جوهره، القلق هو نظام الإنذار في دماغك. عندما تشعر بتهديد ما، يُطلق اللوزة الدماغية إشارات تحرر هرمونات التوتر كالكورتيزول والأدرينالين. تزداد دقات قلبك، ويتسارع تنفسك، وتنقبض عضلاتك — وهي استجابة "القتال أو الفرار" الكلاسيكية. يكون هذا مفيداً عند مواجهة خطر حقيقي، لكنه يصبح إشكالياً عندما يُشغَّل في المواقف اليومية.\n\nتشمل الأعراض الشائعة للقلق: القلق المستمر، صعوبة التركيز، سرعة الانفعال، توتر العضلات، اضطرابات النوم، والأعراض الجسدية كتسارع ضربات القلب أو التعرق. لا يعاني الجميع من القلق بنفس الطريقة، والتعرف على نمطك الشخصي هو المفتاح.\n\nالخبر الجيد هو أن القلق قابل للعلاج بدرجة عالية. ثبت أن العلاج المعرفي السلوكي (CBT)، وممارسات اليقظة الذهنية، والأدوية عند الاقتضاء، والتغييرات في نمط الحياة تُقلل من القلق بشكل ملحوظ. الخطوة الأولى هي الاعتراف بما تمر به والتواصل مع من يمكنه تقديم الدعم.`,
  },
  'anxiety-management-techniques': {
    en: `Managing anxiety effectively requires a toolkit of strategies you can draw on in different situations. Here are seven evidence-based techniques that mental health professionals recommend.\n\nFirst, practice diaphragmatic breathing. Slow, deep breathing activates the parasympathetic nervous system, counteracting the stress response. Try inhaling for 4 counts, holding for 2, and exhaling for 6. Second, progressive muscle relaxation involves systematically tensing and releasing muscle groups, helping your body release physical tension associated with anxiety.\n\nThird, cognitive reframing means challenging anxious thoughts. Ask yourself: "Is this thought based on facts or assumptions? What is the worst realistic outcome? How likely is that?" Often, our catastrophic thinking is far more extreme than reality. Fourth, mindfulness meditation teaches you to observe thoughts without judgment, creating space between stimulus and response.\n\nFifth, regular physical exercise is one of the most powerful anxiety reducers. Even 30 minutes of moderate activity three times a week can significantly reduce symptoms. Sixth, limiting caffeine and alcohol can dramatically improve anxiety levels, as both substances amplify the nervous system's excitability. Seventh, social support — talking to a trusted friend, family member, or therapist — helps reduce the burden of anxiety and provides perspective.`,
    ar: `تتطلب إدارة القلق بفاعلية مجموعة من الاستراتيجيات التي يمكنك الاستعانة بها في مواقف مختلفة. فيما يلي سبع تقنيات مبنية على الأدلة يوصي بها متخصصو الصحة النفسية.\n\nأولاً: مارس التنفس الحجابي. يُنشط التنفس العميق البطيء الجهاز العصبي السمبثاوي، مما يُعادل استجابة التوتر. جرب الشهيق لأربع عدات، ثم الاحتباس لعدتين، ثم الزفير لست عدات. ثانياً: يتضمن الاسترخاء العضلي التدريجي شد مجموعات العضلات وإرخاءها بشكل منهجي، مما يساعد جسمك على تحرير التوتر الجسدي المرتبط بالقلق.\n\nثالثاً: إعادة الصياغة المعرفية تعني تحدي الأفكار القلقة. اسأل نفسك: "هل هذه الفكرة مبنية على حقائق أم افتراضات؟ ما هي أسوأ نتيجة واقعية محتملة؟ ما مدى احتمالية حدوث ذلك؟" غالباً ما تكون تفكيرنا الكارثي أكثر تطرفاً بكثير من الواقع. رابعاً: التأمل الذهني يعلمك مراقبة الأفكار دون إصدار أحكام، مما يخلق مسافة بين المحفز والاستجابة.\n\nخامساً: ممارسة التمارين الرياضية المنتظمة هي أحد أقوى مُخففات القلق. حتى 30 دقيقة من النشاط المعتدل ثلاث مرات أسبوعياً يمكن أن تُقلل من الأعراض بشكل ملحوظ. سادساً: تقليل الكافيين والكحول يمكن أن يُحسّن مستويات القلق بشكل كبير. سابعاً: الدعم الاجتماعي — التحدث مع صديق موثوق أو أحد أفراد العائلة أو معالج نفسي — يساعد على تخفيف عبء القلق وتوفير منظور أوسع.`,
  },
  'signs-of-depression': {
    en: `Depression is more than just feeling sad. It is a complex mental health condition that affects how you think, feel, and function in daily life. Recognizing its signs is crucial for getting the right support.\n\nThe core symptoms of depression include persistent low mood lasting more than two weeks, loss of interest or pleasure in activities you once enjoyed (called anhedonia), significant changes in appetite or weight, sleep disturbances (either sleeping too much or too little), fatigue or loss of energy, feelings of worthlessness or excessive guilt, difficulty thinking or concentrating, and in severe cases, thoughts of death or suicide.\n\nDepression also has physical manifestations. Many people experience unexplained aches and pains, digestive issues, or a general feeling of physical heaviness. These somatic symptoms are often overlooked but are a real part of the depressive experience.\n\nIf you recognize these signs in yourself or someone you care about, the most important step is to seek professional support. Depression is highly treatable — with therapy, medication, or a combination of both, the majority of people experience significant improvement. You do not have to face this alone. Reaching out to a mental health professional, your doctor, or a trusted person in your life is a courageous and important first step.`,
    ar: `الاكتئاب أكثر من مجرد شعور بالحزن. إنه حالة نفسية معقدة تؤثر على كيفية تفكيرك وشعورك وأدائك في الحياة اليومية. التعرف على علاماته أمر بالغ الأهمية للحصول على الدعم المناسب.\n\nتشمل الأعراض الأساسية للاكتئاب: المزاج المنخفض المستمر لأكثر من أسبوعين، وفقدان الاهتمام أو المتعة في الأنشطة التي كنت تستمتع بها (يُسمى انعدام المتعة)، والتغيرات الملحوظة في الشهية أو الوزن، واضطرابات النوم، والتعب وفقدان الطاقة، والشعور بانعدام القيمة أو الذنب المفرط، وصعوبة التفكير أو التركيز، وفي الحالات الشديدة، أفكار حول الموت أو الانتحار.\n\nللاكتئاب أيضاً مظاهر جسدية. يعاني كثير من الأشخاص من آلام غير مبررة، أو مشاكل هضمية، أو شعور عام بالثقل الجسدي. هذه الأعراض الجسدية كثيراً ما يتم تجاهلها لكنها جزء حقيقي من تجربة الاكتئاب.\n\nإذا تعرفت على هذه العلامات في نفسك أو في شخص تهتم به، فإن أهم خطوة هي طلب الدعم المتخصص. الاكتئاب قابل للعلاج بدرجة عالية — من خلال العلاج النفسي أو الأدوية أو الجمع بينهما، يشهد الغالبية العظمى من الناس تحسناً ملحوظاً. لست مضطراً لمواجهة هذا وحدك.`,
  },
  'overcoming-depression-daily-habits': {
    en: `While professional treatment is essential for depression, certain daily habits can powerfully support your recovery and wellbeing. Think of these as lifestyle medicine — small actions that compound over time.\n\nStart with movement. Exercise is one of the most evidence-supported interventions for depression. It releases endorphins, reduces cortisol, and promotes neuroplasticity. You do not need intense workouts — even a 20-minute walk in nature has measurable effects on mood. Aim for consistency over intensity.\n\nSunlight and circadian rhythm regulation play a significant role in mood. Try to get morning sunlight within an hour of waking. This helps regulate your body clock and boosts serotonin production. Maintaining a consistent sleep schedule — going to bed and waking at the same time — is equally important.\n\nSocial connection is also critical. Depression tends to drive isolation, but isolation deepens depression. Even small interactions — a brief conversation with a friend, joining a group activity — can break the cycle. Finally, engage in structured activities, even when motivation is absent. "Behavioral activation" — the practice of scheduling meaningful activities — is a cornerstone of CBT for depression. Action precedes motivation, not the other way around.`,
    ar: `بينما يُعدّ العلاج المتخصص ضرورياً لعلاج الاكتئاب، إلا أن بعض العادات اليومية يمكنها دعم تعافيك ورفاهيتك بشكل قوي. فكر في هذه العادات كدواء لنمط الحياة — إجراءات صغيرة تتراكم تأثيراتها بمرور الوقت.\n\nابدأ بالحركة. تعد ممارسة الرياضة من أكثر التدخلات الثابتة علمياً لعلاج الاكتئاب. تُطلق الإندورفين، وتُقلل الكورتيزول، وتعزز مرونة الدماغ. لست بحاجة إلى تمارين مكثفة — حتى المشي لمدة 20 دقيقة في الطبيعة له تأثيرات قابلة للقياس على المزاج.\n\nيلعب ضوء الشمس وتنظيم الإيقاع اليومي دوراً مهماً في المزاج. حاول الحصول على ضوء الشمس الصباحي في غضون ساعة من الاستيقاظ. كما يُعدّ الحفاظ على جدول نوم منتظم أمراً بالغ الأهمية.\n\nالتواصل الاجتماعي أيضاً أمر حيوي. يميل الاكتئاب إلى دفع الشخص نحو العزلة، لكن العزلة تُعمّق الاكتئاب. حتى التفاعلات الصغيرة يمكنها كسر هذه الحلقة. أخيراً، انخرط في أنشطة منظمة حتى عندما يغيب الدافع. "التنشيط السلوكي" — ممارسة جدولة الأنشطة المعنوية — هو حجر الزاوية في العلاج المعرفي السلوكي للاكتئاب. العمل يسبق الدافع، وليس العكس.`,
  },
  'stress-relief-techniques': {
    en: `Stress is an inevitable part of life, but chronic stress causes real harm to your physical and mental health. These five evidence-based techniques are clinically proven to reduce stress and improve wellbeing.\n\nThe first technique is mindfulness meditation. Regular mindfulness practice — even 10 minutes daily — has been shown in numerous studies to lower cortisol levels, reduce anxiety, and improve emotional regulation. Apps, guided meditations, or simple breath-focused practice can all help you get started.\n\nSecond, time in nature. Research consistently shows that spending time in natural settings reduces stress hormones, lowers blood pressure, and improves mood. A practice called "forest bathing" (Shinrin-yoku) from Japan has been particularly well-studied. Even urban green spaces can provide benefit.\n\nThird, journaling. Writing about stressful experiences helps process emotions and gain perspective. Studies show that expressive writing can reduce psychological distress and even improve immune function. Try writing for 15-20 minutes about what is stressing you and how you feel about it.\n\nFourth, social connection. Strong social bonds are one of the most powerful buffers against stress. Talking to a trusted friend or loved one activates oxytocin, which counteracts cortisol. Fifth, progressive relaxation and body scan practices help release the physical tension that stress creates in your body, providing immediate relief and training your nervous system toward calm.`,
    ar: `التوتر جزء لا مفر منه في الحياة، لكن التوتر المزمن يُلحق ضرراً حقيقياً بصحتك الجسدية والنفسية. هذه التقنيات الخمس المبنية على الأدلة مثبتة سريرياً لتقليل التوتر وتحسين الرفاهية.\n\nالتقنية الأولى هي التأمل الذهني. ثبت في دراسات عديدة أن ممارسة اليقظة الذهنية المنتظمة — ولو 10 دقائق يومياً — تخفض مستويات الكورتيزول، وتقلل القلق، وتحسن التنظيم العاطفي.\n\nثانياً، قضاء الوقت في الطبيعة. تُظهر الأبحاث باستمرار أن قضاء الوقت في البيئات الطبيعية يُقلل هرمونات التوتر، ويخفض ضغط الدم، ويُحسّن المزاج.\n\nثالثاً، الكتابة في مذكرات. كتابة التجارب المُجهِدة تساعد على معالجة العواطف واكتساب منظور أوسع. أظهرت الدراسات أن الكتابة التعبيرية يمكن أن تُقلل الضيق النفسي وتُحسّن حتى وظيفة المناعة.\n\nرابعاً، التواصل الاجتماعي. الروابط الاجتماعية القوية هي أحد أقوى حمايات الحماية من التوتر. التحدث مع صديق موثوق أو أحد أفراد العائلة يُنشّط الأوكسيتوسين الذي يُعادل الكورتيزول. خامساً، ممارسة الاسترخاء التدريجي ومسح الجسم تساعد على تحرير التوتر الجسدي الذي يُحدثه الضغط في جسمك.`,
  },
  'workplace-stress-management': {
    en: `Workplace stress is now recognized as a global health crisis. Long hours, demanding deadlines, difficult relationships, and lack of autonomy can all contribute to burnout and mental health deterioration. Managing this stress requires both individual strategies and systemic awareness.\n\nSetting clear boundaries is foundational. This means defining your working hours and communicating them clearly, learning to say no to requests that exceed your capacity, and protecting non-work time as sacred recovery space. Many people find this difficult, particularly in cultures that glorify overwork, but boundaries are not a luxury — they are a necessity.\n\nPrioritization is equally important. Not all tasks are equal. Using frameworks like the Eisenhower Matrix (urgent vs. important) helps you focus on what truly matters and let go of tasks that consume energy without meaningful impact.\n\nWorkplace relationships also play a major role. Conflict with colleagues or managers is a significant source of stress. Developing skills in assertive communication — expressing your needs clearly and respectfully — can transform these dynamics. Finally, micro-recovery practices throughout the day — short breaks, brief walks, mindful breathing — help prevent the accumulation of stress that leads to burnout.`,
    ar: `بات التوتر في بيئة العمل يُعترف به على أنه أزمة صحية عالمية. يمكن لساعات العمل الطويلة، والمواعيد النهائية المطلوبة، والعلاقات الصعبة، وانعدام الاستقلالية أن تُسهم جميعها في الإرهاق وتدهور الصحة النفسية.\n\nيعدّ تحديد الحدود الواضحة أمراً أساسياً. يعني ذلك تحديد ساعات عملك والتواصل بشأنها بوضوح، وتعلم قول "لا" للطلبات التي تتجاوز قدرتك، وحماية وقت عدم العمل كمساحة تعافي مقدسة.\n\nتحديد الأولويات لا يقل أهمية. ليست جميع المهام متساوية. يساعدك استخدام أطر مثل مصفوفة إيزنهاور (العاجل مقابل المهم) على التركيز على ما يهم حقاً والتخلص من المهام التي تستهلك الطاقة دون تأثير ذي معنى.\n\nتُؤدي علاقات مكان العمل أيضاً دوراً رئيسياً. يُعدّ الصراع مع الزملاء أو المديرين مصدراً مهماً للتوتر. أخيراً، ممارسات التعافي الصغيرة طوال اليوم — استراحات قصيرة، وجولات قصيرة، والتنفس الواعي — تساعد على منع تراكم التوتر الذي يؤدي إلى الإرهاق.`,
  },
  'better-sleep-habits': {
    en: `Sleep is not a luxury — it is a biological necessity. During sleep, your brain consolidates memories, clears toxic waste products, regulates emotions, and restores energy. Poor sleep is one of the most significant contributors to mental health problems, including depression and anxiety.\n\nThe foundation of better sleep is sleep hygiene — a set of consistent behavioral practices that signal to your brain and body that it is time to sleep. The most important is consistency: going to bed and waking at the same time every day, including weekends, anchors your circadian rhythm.\n\nYour sleep environment matters profoundly. The ideal bedroom is cool (around 18°C/65°F), dark, and quiet. Blackout curtains, white noise machines, or earplugs can help create this environment. Reserve your bed for sleep and sex only — working or watching content in bed trains your brain to associate the bed with wakefulness.\n\nWind-down routines signal to your nervous system that sleep is approaching. A consistent 30-60 minute routine before bed — including dimming lights, avoiding screens, reading, or gentle stretching — reduces alertness and promotes melatonin production. Avoid caffeine after 2pm and alcohol within 3 hours of bedtime, as both significantly disrupt sleep architecture.`,
    ar: `النوم ليس رفاهية — إنه ضرورة بيولوجية. أثناء النوم، يُوطّد الدماغ الذكريات، ويُزيل منتجات النفايات السامة، وينظم المشاعر، ويُعيد الطاقة. يُعدّ ضعف النوم أحد أكثر المساهمين في مشاكل الصحة النفسية، بما فيها الاكتئاب والقلق.\n\nأساس النوم الأفضل هو نظافة النوم — مجموعة من الممارسات السلوكية المتسقة التي تُشير إلى دماغك وجسمك بأن وقت النوم قد حان. الأهم هو الاتساق: النوم والاستيقاظ في نفس الوقت كل يوم، بما في ذلك عطل نهاية الأسبوع، يرسّخ إيقاعك اليومي.\n\nبيئة النوم مهمة للغاية. غرفة النوم المثالية باردة (حوالي 18 درجة مئوية)، ومظلمة، وهادئة. احتفظ بسريرك للنوم فقط — العمل أو مشاهدة المحتوى في السرير يُدرّب دماغك على ربط السرير باليقظة.\n\nروتين الاسترخاء قبل النوم يُشير إلى جهازك العصبي بأن النوم يقترب. تجنب الكافيين بعد الساعة الثانية ظهراً والكحول خلال ثلاث ساعات من موعد النوم، لأن كليهما يُعطل بنية النوم بشكل ملحوظ.`,
  },
  'insomnia-causes-solutions': {
    en: `Insomnia — difficulty falling asleep, staying asleep, or waking too early — affects approximately one-third of adults at some point in their lives. While occasional sleeplessness is normal, chronic insomnia lasting three or more nights per week for at least three months requires attention.\n\nInsomnia has many causes. Psychological factors are the most common: anxiety, depression, and stress all disrupt sleep. Racing thoughts at bedtime, worrying about not sleeping, and hyperarousal of the nervous system create a cycle that perpetuates insomnia even after the initial trigger has resolved.\n\nMedical conditions can also cause insomnia, including chronic pain, sleep apnea, restless legs syndrome, acid reflux, and certain medications. Lifestyle factors like irregular schedules, excessive screen time, caffeine, and alcohol are also significant contributors.\n\nThe most effective treatment for chronic insomnia is Cognitive Behavioral Therapy for Insomnia (CBT-I), which is more effective long-term than medication. CBT-I addresses the thoughts and behaviors that perpetuate insomnia, including sleep restriction therapy, stimulus control, and cognitive restructuring of sleep-related beliefs. If you suspect your insomnia is chronic, speaking with a healthcare provider or sleep specialist is strongly recommended.`,
    ar: `الأرق — صعوبة في النوم أو البقاء نائماً أو الاستيقاظ مبكراً جداً — يؤثر على ما يقارب ثلث البالغين في مرحلة ما من حياتهم. بينما يُعدّ الأرق المتقطع أمراً طبيعياً، فإن الأرق المزمن الذي يستمر ثلاث ليالٍ أو أكثر أسبوعياً لمدة ثلاثة أشهر على الأقل يتطلب الاهتمام.\n\nللأرق أسباب عديدة. العوامل النفسية هي الأكثر شيوعاً: القلق والاكتئاب والتوتر كلها تُعطل النوم. أفكار متسارعة وقت النوم، والقلق من عدم النوم، وفرط استثارة الجهاز العصبي تُنشئ دورة تُديم الأرق حتى بعد زوال المحفز الأصلي.\n\nيمكن للحالات الطبية أيضاً أن تُسبب الأرق، بما فيها الألم المزمن، وانقطاع النفس أثناء النوم، ومتلازمة تململ الساقين، والحموضة المعوية، وبعض الأدوية.\n\nالعلاج الأكثر فعالية للأرق المزمن هو العلاج المعرفي السلوكي للأرق (CBT-I)، وهو أكثر فعالية على المدى البعيد من الأدوية. إذا كنت تشك في أن أرقك مزمن، فإن التحدث مع مقدم الرعاية الصحية أو أخصائي النوم يُوصى به بشدة.`,
  },
  'living-well-with-adhd': {
    en: `Attention Deficit Hyperactivity Disorder (ADHD) is a neurodevelopmental condition characterized by differences in attention regulation, impulse control, and activity level. It is important to understand that ADHD is not a character flaw, a lack of willpower, or a result of poor parenting — it is a legitimate neurological difference with both challenges and unique strengths.\n\nPeople with ADHD often have exceptional creativity, out-of-the-box thinking, high energy, and the ability to hyperfocus on topics they find deeply interesting. These strengths, when channeled effectively, can become significant advantages. Many artists, entrepreneurs, and innovators have ADHD.\n\nLiving well with ADHD involves understanding your own cognitive profile. What conditions help you focus? What times of day are you most alert? What environments are most conducive to your work? Building systems that work with your brain rather than against it is key.\n\nExternal structure is particularly helpful: calendars, reminders, deadlines, accountability partners, and organized physical spaces reduce the cognitive load of self-management. Exercise is especially beneficial for ADHD, as it increases dopamine and norepinephrine — the same neurotransmitters that ADHD medications target. Professional support — including therapy, coaching, and where appropriate, medication — can significantly improve quality of life.`,
    ar: `اضطراب نقص الانتباه وفرط الحركة (ADHD) هو حالة عصبية نمائية تتميز باختلافات في تنظيم الانتباه، والتحكم في الاندفاع، ومستوى النشاط. من المهم أن نفهم أن هذا الاضطراب ليس عيباً في الشخصية، أو غياباً لإرادة القوة، أو نتيجة لسوء التربية — بل هو اختلاف عصبي حقيقي له تحدياته ونقاط قوته الفريدة.\n\nكثيراً ما يتمتع الأشخاص المصابون بهذا الاضطراب بإبداع استثنائي، وتفكير خارج الصندوق، وطاقة عالية، وقدرة على التركيز المكثف على المواضيع التي يجدونها مثيرة للاهتمام بشكل عميق.\n\nالعيش بشكل جيد مع هذا الاضطراب يتضمن فهم ملفك المعرفي الخاص. ما الظروف التي تساعدك على التركيز؟ ما أوقات اليوم التي تكون فيها أكثر يقظة؟ ما البيئات الأكثر ملاءمة لعملك؟ بناء أنظمة تعمل مع دماغك وليس ضده هو المفتاح.\n\nالهيكل الخارجي مفيد بشكل خاص: التقاويم والتذكيرات والمواعيد النهائية وشركاء المساءلة والمساحات الجسدية المنظمة تُقلل العبء المعرفي لإدارة الذات. تمارين الرياضة مفيدة بشكل خاص لهذا الاضطراب، لأنها تزيد من الدوبامين والنورإبينفرين.`,
  },
  'adhd-focus-productivity': {
    en: `For people with ADHD, traditional productivity advice often falls flat because it was designed for neurotypical brains. Managing focus with ADHD requires strategies tailored to how your brain actually works.\n\nThe Pomodoro Technique — working in focused 25-minute intervals with short breaks — is particularly effective for ADHD because it creates artificial deadlines and regular reset points. Many people with ADHD find that external accountability dramatically improves focus: body doubling (working alongside someone else), co-working spaces, or virtual accountability sessions can be transformative.\n\nReducing friction in your environment is critical. This means setting up your workspace so that the task in front of you is the easiest thing to do. Put your materials out the night before. Close browser tabs. Use website blockers during focus time. Declutter your physical space.\n\nTask initiation is often the hardest part for ADHD brains. The "two-minute rule" — if a task takes less than two minutes, do it immediately — helps break inertia. For larger tasks, breaking them into the smallest possible steps and committing to just the first step can overcome the starting barrier. Finally, working with your energy rhythms rather than against them — scheduling demanding tasks for your peak hours — is essential.`,
    ar: `بالنسبة للأشخاص المصابين باضطراب نقص الانتباه، كثيراً ما تفشل نصائح الإنتاجية التقليدية لأنها صُممت لأدمغة عادية. تتطلب إدارة التركيز مع هذا الاضطراب استراتيجيات مصممة لكيفية عمل دماغك فعلياً.\n\nتقنية بومودورو — العمل في فترات مركزة مدتها 25 دقيقة مع استراحات قصيرة — فعّالة بشكل خاص لأنها تخلق مواعيد نهائية اصطناعية ونقاط إعادة ضبط منتظمة. يجد كثير من الأشخاص المصابين بهذا الاضطراب أن المساءلة الخارجية تُحسّن التركيز بشكل كبير.\n\nتقليل الاحتكاك في بيئتك أمر بالغ الأهمية. يعني ذلك إعداد مساحة عملك بحيث تكون المهمة التي أمامك أسهل شيء يمكن القيام به. أغلق علامات تبويب المتصفح. استخدم برامج حظر المواقع خلال وقت التركيز. قلل الفوضى في مساحتك الجسدية.\n\nبدء المهمة هو في الغالب الجزء الأصعب لأدمغة هذا الاضطراب. "قاعدة الدقيقتين" — إذا استغرقت مهمة أقل من دقيقتين، افعلها فوراً — تساعد على كسر القصور الذاتي. بالنسبة للمهام الأكبر، تقسيمها إلى أصغر خطوات ممكنة والالتزام بالخطوة الأولى فقط يمكنه التغلب على حاجز البدء.`,
  },
  'healthy-communication-patterns': {
    en: `Healthy communication is the foundation of all meaningful relationships — romantic partnerships, friendships, family ties, and professional connections. Poor communication is consistently cited as the primary cause of relationship breakdown, while effective communication predicts relationship satisfaction and longevity.\n\nThe most important communication skill is active listening — truly attending to what the other person is saying, without formulating your response while they speak. Active listening involves maintaining eye contact, asking clarifying questions, reflecting back what you heard, and validating the other person's experience even when you disagree.\n\nAssertive communication — the middle ground between passivity and aggression — is essential. This means expressing your thoughts, feelings, and needs clearly and respectfully, using "I" statements ("I feel hurt when..." rather than "You always..."), and requesting specific changes rather than attacking character.\n\nNonviolent communication (NVC), developed by Marshall Rosenberg, offers a powerful framework: observe without evaluating, identify your feelings, identify the underlying need, and make a concrete request. Practicing this approach can transform conflict into connection. Finally, understanding that repair — the ability to acknowledge mistakes and reconnect after conflict — is more important than never having conflict. All relationships experience friction; healthy ones know how to recover.`,
    ar: `التواصل الصحي هو أساس جميع العلاقات الهادفة — الشراكات الرومانسية، والصداقات، وروابط الأسرة، والعلاقات المهنية. يُستشهد باستمرار بضعف التواصل باعتباره السبب الرئيسي لانهيار العلاقات، بينما يتنبأ التواصل الفعّال برضا العلاقة ومدتها.\n\nأهم مهارة تواصل هي الاستماع الفعّال — الاهتمام الحقيقي بما يقوله الشخص الآخر، دون صياغة ردك أثناء حديثه. يتضمن الاستماع الفعّال الحفاظ على التواصل البصري، وطرح أسئلة توضيحية، وعكس ما سمعته، والتحقق من صحة تجربة الشخص الآخر حتى عندما تختلف معه.\n\nالتواصل الحازم — الوسط بين السلبية والعدوانية — ضروري. يعني ذلك التعبير عن أفكارك ومشاعرك واحتياجاتك بوضوح واحترام، باستخدام عبارات "أنا" بدلاً من "أنت دائماً...".\n\nالتواصل اللاعنيف (NVC) الذي طوره مارشال روزنبرغ يقدم إطاراً قوياً: الملاحظة دون تقييم، وتحديد مشاعرك، وتحديد الحاجة الكامنة، وتقديم طلب محدد. يمكن لممارسة هذا النهج أن تُحوّل الصراع إلى تواصل.`,
  },
  'setting-boundaries-in-relationships': {
    en: `Boundaries are the invisible lines that define where you end and another person begins. They are not walls to keep people out, but guidelines that communicate your values, limits, and needs. Setting healthy boundaries is an act of self-respect and is fundamental to all healthy relationships.\n\nBoundaries can be physical (personal space and touch), emotional (what you are willing to discuss and how you want to be spoken to), time-related (how you allocate your time and energy), digital (availability and communication expectations), and material (how you handle possessions and finances).\n\nMany people struggle to set boundaries due to fear of conflict, guilt, people-pleasing tendencies, or cultural or family programming that equated boundaries with selfishness. However, boundaries are not selfish — they are what make sustainable, mutual relationships possible. Without them, resentment builds, energy depletes, and relationships deteriorate.\n\nSetting a boundary involves being clear, direct, and consistent. State your limit ("I am not available after 8pm"), explain the reason briefly if appropriate, and follow through consistently. Expect pushback — especially from people who were accustomed to having no limits with you. The discomfort of enforcing boundaries is temporary; the relief and self-respect that follow are lasting.`,
    ar: `الحدود هي الخطوط غير المرئية التي تُحدد أين تنتهي أنت وأين يبدأ شخص آخر. إنها ليست جدراناً لإبعاد الناس، بل مبادئ توجيهية تُوصّل قيمك وحدودك واحتياجاتك. وضع حدود صحية هو فعل احترام للذات وأساسي لجميع العلاقات الصحية.\n\nيمكن أن تكون الحدود جسدية (المساحة الشخصية واللمس)، وعاطفية (ما تكون على استعداد لمناقشته وكيف تريد أن يُتحدث معك)، ومتعلقة بالوقت (كيف تُخصص وقتك وطاقتك)، ورقمية (توقعات التوافر والتواصل)، ومادية (كيف تتعامل مع الممتلكات والشؤون المالية).\n\nيُعاني كثير من الأشخاص من صعوبة وضع الحدود بسبب الخوف من الصراع، أو الشعور بالذنب، أو ميول إرضاء الآخرين، أو البرمجة الثقافية والعائلية التي تساوي بين الحدود والأنانية. لكن الحدود ليست أنانية — بل هي ما يجعل العلاقات المتبادلة المستدامة ممكنة.\n\nوضع حد يتضمن أن تكون واضحاً ومباشراً ومتسقاً. اذكر حدك بوضوح، واشرح السبب باختصار إذا كان مناسباً، والتزم به باستمرار. توقع ردود فعل مضادة — خاصة من الأشخاص الذين اعتادوا على عدم وجود حدود معك. انزعاج تطبيق الحدود مؤقت؛ أما الارتياح واحترام الذات اللذان يعقبان ذلك فهما دائمان.`,
  },
}

export default function ResourceArticleScreen() {
  const { slug } = useLocalSearchParams<{ slug: string }>()
  const router = useRouter()
  const { lang } = useLocale()
  const isRTL = useIsRTL(lang)

  const resource = RESOURCES.find(r => r.slug === slug)
  const content = slug ? ARTICLE_CONTENT[slug] : null

  if (!resource) {
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.notFound}>
          <Text style={styles.notFoundText}>{t('error', lang)}</Text>
          <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
            <Text style={styles.backBtnText}>{t('back', lang)}</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    )
  }

  const title = lang === 'ar' ? resource.titleAr : resource.titleEn
  const paragraphs = (lang === 'ar' ? content?.ar : content?.en)?.split('\n\n') ?? []

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView contentContainerStyle={styles.scroll}>
        {/* Back button */}
        <TouchableOpacity
          onPress={() => router.back()}
          style={[styles.backRow, isRTL && styles.rtlRow]}
        >
          <Ionicons name={isRTL ? 'arrow-forward' : 'arrow-back'} size={20} color="#1D6296" />
          <Text style={[styles.backText, isRTL && { marginRight: 6 }]}>{t('back', lang)}</Text>
        </TouchableOpacity>

        {/* Article header */}
        <Text style={styles.articleIcon}>{resource.icon}</Text>
        <Text style={[styles.articleTitle, isRTL && styles.rtlText]}>{title}</Text>
        <View style={[styles.metaRow, isRTL && styles.rtlRow]}>
          <View style={[styles.categoryBadge, { backgroundColor: '#EBF4FA' }]}>
            <Text style={[styles.categoryText, { color: '#1D6296' }]}>
              {t(resource.category as any, lang)}
            </Text>
          </View>
          <Text style={styles.readingTimeText}>
            {t('readingTime', lang, { min: resource.readingTimeMin })}
          </Text>
        </View>

        {/* Divider */}
        <View style={styles.divider} />

        {/* Content paragraphs */}
        {paragraphs.map((para, idx) => (
          <Text key={idx} style={[styles.paragraph, isRTL && styles.rtlText]}>
            {para}
          </Text>
        ))}

        {/* Disclaimer */}
        <View style={styles.disclaimer}>
          <Ionicons name="information-circle-outline" size={16} color="#6B7280" />
          <Text style={[styles.disclaimerText, isRTL && styles.rtlText]}>
            {lang === 'ar'
              ? 'هذه المقالة لأغراض تعليمية فقط وليست بديلاً عن الاستشارة المهنية.'
              : 'This article is for educational purposes only and is not a substitute for professional advice.'}
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  )
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F9FAFB' },
  scroll: { padding: 16, paddingBottom: 48 },
  notFound: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 16 },
  notFoundText: { fontSize: 16, color: '#6B7280' },
  backBtn: { backgroundColor: '#1D6296', paddingHorizontal: 20, paddingVertical: 10, borderRadius: 10 },
  backBtnText: { color: '#FFFFFF', fontWeight: '600' },
  backRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 20 },
  rtlRow: { flexDirection: 'row-reverse' },
  rtlText: { writingDirection: 'rtl', textAlign: 'right' },
  backText: { color: '#1D6296', fontSize: 14, fontWeight: '500', marginLeft: 6 },
  articleIcon: { fontSize: 48, marginBottom: 12 },
  articleTitle: { fontSize: 22, fontWeight: '800', color: '#111827', lineHeight: 30, marginBottom: 12 },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 20 },
  categoryBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },
  categoryText: { fontSize: 12, fontWeight: '600' },
  readingTimeText: { fontSize: 12, color: '#9CA3AF' },
  divider: { height: 1, backgroundColor: '#E5E7EB', marginBottom: 20 },
  paragraph: { fontSize: 15, color: '#374151', lineHeight: 26, marginBottom: 16 },
  disclaimer: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, backgroundColor: '#F3F4F6', borderRadius: 12, padding: 12, marginTop: 24 },
  disclaimerText: { fontSize: 12, color: '#6B7280', lineHeight: 18, flex: 1 },
})
