#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Local Supabase bootstrap for V Welfare development.
#
# Why this exists:
#   `supabase/migrations/20260619120000_schema_baseline.sql` is a snapshot of
#   the already-deployed remote schema. It uses `CREATE TABLE IF NOT EXISTS`
#   and defines `public.assessment_submissions` (which has a foreign key to
#   `public.assessment_assignments`) BEFORE it defines
#   `public.assessment_assignments`. On the remote database every table already
#   existed, so the forward reference was a harmless no-op. On a brand-new local
#   database the referenced table does not exist yet, so `supabase start`/
#   `supabase db reset` aborts with:
#       ERROR: relation "public.assessment_assignments" does not exist
#
#   To keep the tracked migration files pristine (they document the schema
#   "as deployed"), this script builds a throwaway copy of the `supabase/`
#   project in a cache directory, reorders ONLY those two table blocks in the
#   copy, and runs `supabase start` against the copy. The local database ends
#   up identical; only the apply order is corrected.
#
# Usage:
#   ./scripts/dev-local-supabase.sh start   # start (default)
#   ./scripts/dev-local-supabase.sh stop
#   ./scripts/dev-local-supabase.sh status
# ---------------------------------------------------------------------------
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="${VW_SUPABASE_BUILD_DIR:-$HOME/.cache/vw-local-supabase}"
CMD="${1:-start}"

reorder_baseline() {
  python3 - "$1" <<'PY'
import sys, re
path = sys.argv[1]
with open(path, "r", encoding="utf-8") as f:
    text = f.read()

sub_marker = "CREATE TABLE IF NOT EXISTS public.assessment_submissions ("
asg_marker = "CREATE TABLE IF NOT EXISTS public.assessment_assignments ("
sub_i = text.find(sub_marker)
asg_i = text.find(asg_marker)
if sub_i == -1 or asg_i == -1 or asg_i < sub_i:
    # Nothing to do (already ordered or markers changed).
    sys.exit(0)

# Extract the full assessment_assignments block: from its CREATE to the first
# line that is exactly ");" terminating that statement.
end_i = text.find("\n);", asg_i)
if end_i == -1:
    sys.exit(0)
block_end = end_i + len("\n);")
block = text[asg_i:block_end].rstrip("\n")

# Remove the block from its original position and re-insert it before the
# assessment_submissions block.
new_text = text[:asg_i] + text[block_end:]
new_text = new_text[:sub_i] + block + "\n\n" + new_text[sub_i:]
with open(path, "w", encoding="utf-8") as f:
    f.write(new_text)
print("reordered assessment_assignments before assessment_submissions")
PY
}

# The admin-dashboard materialized-view migration is broken for any fresh
# database: it references profiles.user_type / profiles.full_name / profiles.email
# (none exist in the baseline — the column is `role`, names are split *_en/*_ar,
# and email lives in auth.users) and contains SQL syntax errors (stray quotes).
# It only ever "applied" on remote because the objects pre-existed and
# CREATE MATERIALIZED VIEW IF NOT EXISTS short-circuited. Its unguarded REVOKE
# follow-up then also fails locally when the matviews are absent. Neutralise both
# in the throwaway copy so the rest of the schema applies. The later security-
# hardening migrations already guard their matview grants with IF EXISTS, so they
# remain safe. Effect: admin analytics dashboards that read these matviews are
# unavailable locally; the core patient/auth flow is unaffected.
neutralize() {
  local file="$1" reason="$2"
  if [ -f "$file" ]; then
    printf -- '-- Neutralised for local development by scripts/dev-local-supabase.sh\n-- %s\n' "$reason" > "$file"
  fi
}

# The signup trigger on auth.users is missing on a fresh rebuild: the baseline
# creates `on_auth_user_created`, but 20260619210813_fix_duplicate_auth_trigger
# DROPs it and relies on `trg_on_auth_user_created` — which was only ever created
# out-of-band on remote (its migration, 20260618122343_create_patient_profile_on_signup,
# is a 2-line stub). Result: no trigger fires on signup and registration fails
# with "Database error saving new user". Restore it via seed.sql (runs after
# migrations on `supabase db reset`). This mirrors the intended production state.
write_seed() {
  cat > "$1" <<'SQL'
-- Local-dev seed generated by scripts/dev-local-supabase.sh
-- Restore the signup trigger that fresh rebuilds drop (see script header).
DROP TRIGGER IF EXISTS trg_on_auth_user_created ON auth.users;
CREATE TRIGGER trg_on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
SQL
}

build_copy() {
  mkdir -p "$BUILD_DIR"
  rm -rf "$BUILD_DIR/supabase"
  cp -r "$REPO_ROOT/supabase" "$BUILD_DIR/supabase"
  reorder_baseline "$BUILD_DIR/supabase/migrations/20260619120000_schema_baseline.sql"
  write_seed "$BUILD_DIR/supabase/seed.sql"
  neutralize "$BUILD_DIR/supabase/migrations/20260627220000_admin_dashboard_materialized_views.sql" \
    "admin matviews reference non-existent columns (user_type/full_name/email) and contain SQL syntax errors"
  neutralize "$BUILD_DIR/supabase/migrations/20260628071704_revoke_admin_matview_api_access.sql" \
    "unguarded REVOKE on admin matviews that are not created locally"
}

case "$CMD" in
  start)
    build_copy
    supabase start --workdir "$BUILD_DIR"
    ;;
  stop)
    supabase stop --workdir "$BUILD_DIR" "${@:2}"
    ;;
  status)
    supabase status --workdir "$BUILD_DIR"
    ;;
  *)
    echo "Usage: $0 {start|stop|status}" >&2
    exit 1
    ;;
esac
